trigger:
- master

pool:
  vmImage: "ubuntu-18.04"

steps:
- script: python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
    pip install pytest
    python -m pytest
  displayName: 'Test with pytest'

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: "official-docker-modmoto"
    repository: "modmoto/w3champions-mmr-service"
    command: "buildAndPush"
    buildContext: "."
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest