trigger:
- master

pool:
  vmImage: "ubuntu-18.04"

steps:
- script: |
    python -m pip install --upgrade pip setuptools wheel
  displayName: 'Install tools'

- script: |
    pip install pytest
    pip install pytest-cov
    python -m pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml --cov-report=html
  displayName: 'Test with pytest'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Publish test results for Python $(python.version)'

- task: Docker@2
  displayName: Build an image
  inputs:
    containerRegistry: "official-docker-modmoto"
    repository: "modmoto/w3champions-mmr-service"
    command: "buildAndPush"
    buildContext: "."
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest